import { StyleSheet, Platform } from "react-native";
import { colors } from "@/constants/colors";

const webFont = Platform.select({ web: "'Inter', system-ui, sans-serif", default: undefined });
const displayFont = Platform.select({ web: "'Lexend', 'Inter', system-ui", default: undefined });

const cardShadow = Platform.select({
  ios: { shadowColor: "#7C3AED", shadowOpacity: 0.08, shadowRadius: 24, shadowOffset: { width: 0, height: 8 } },
  android: { elevation: 4 },
  web: { boxShadow: "0 8px 32px rgba(124, 58, 237, 0.08)" },
  default: { elevation: 4 },
});

export const webStyles = StyleSheet.create({
  root: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#FAFAFC",
  },
  sidebarCol: {
    width: 272,
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    borderRightWidth: 1,
    borderRightColor: "rgba(124, 58, 237, 0.1)",
    ...Platform.select({
      web: { boxShadow: "2px 0 24px rgba(124, 58, 237, 0.05)", backdropFilter: "blur(20px)" } as any,
      default: {},
    }),
  },
  contentArea: {
    flex: 1,
    backgroundColor: "#FAFAFC",
  },
  contentInner: {
    paddingHorizontal: 32,
    paddingTop: 28,
    paddingBottom: 48,
  },
  twoCol: {
    flexDirection: "row",
    gap: 20,
    marginBottom: 20,
  },
  colLeft: {
    flex: 1,
  },
  colRight: {
    flex: 1,
  },
});

export const styles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: "#FAFAFC",
  },
  main: {
    flex: 1,
  },
  sectionContainer: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: Platform.OS === "android" ? 48 : 60,
    paddingBottom: 16,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    borderBottomWidth: 1,
    borderBottomColor: "rgba(124, 58, 237, 0.08)",
    position: "relative",
    zIndex: 999,
    ...Platform.select({
      web: {
        height: 72,
        paddingTop: 0,
        paddingBottom: 0,
        paddingHorizontal: 56,
        backgroundColor: "rgba(255, 255, 255, 0.92)",
        backdropFilter: "blur(18px)",
        position: "sticky" as any,
        top: 0,
      } as any,
      default: {},
    }),
  },
  logoText: {
    fontSize: 22,
    fontWeight: "800",
    color: colors.primary,
    fontFamily: displayFont,
    letterSpacing: 1.5,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  webHeaderNav: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "rgba(124, 58, 237, 0.04)",
    padding: 5,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(124, 58, 237, 0.08)",
  },
  webHeaderNavItem: {
    paddingHorizontal: 14,
    paddingVertical: 9,
    borderRadius: 999,
  },
  webHeaderNavItemActive: {
    backgroundColor: "#FFFFFF",
    ...Platform.select({
      web: { boxShadow: "0 8px 20px rgba(124, 58, 237, 0.10)" },
      default: {},
    }),
  },
  webHeaderNavText: {
    color: "#64748B",
    fontSize: 13,
    fontWeight: "800",
    fontFamily: webFont,
  },
  webHeaderNavTextActive: {
    color: colors.primary,
  },
  bellWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F3F4F6",
    alignItems: "center",
    justifyContent: "center",
  },
  badge: {
    position: "absolute",
    top: -2,
    right: -2,
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: colors.accent,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#FFFFFF",
  },
  badgeText: {
    color: "#FFFFFF",
    fontSize: 9,
    fontWeight: "800",
  },
  profileWrapper: {
    position: "relative",
    zIndex: 9999,
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    borderWidth: 1.5,
    borderColor: "rgba(124, 58, 237, 0.2)",
  },
  profileMenu: {
    position: "absolute",
    top: 52,
    right: 0,
    width: 260,
    borderRadius: 24,
    padding: 16,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    ...cardShadow,
    zIndex: 99999,
    borderWidth: 1,
    borderColor: "rgba(124, 58, 237, 0.1)",
  },
  profileTop: {
    flexDirection: "row",
    alignItems: "center",
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.05)",
  },
  profileImg: {
    width: 46,
    height: 46,
    borderRadius: 23,
    marginRight: 12,
  },
  profileName: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.textPrimary,
    fontFamily: displayFont,
  },
  profileSub: {
    marginTop: 2,
    color: colors.textSecondary,
    fontSize: 12,
    fontFamily: webFont,
  },
  profileAction: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    gap: 12,
  },
  profileLogout: {
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.05)",
    paddingTop: 12,
  },
  profileActionText: {
    fontSize: 14,
    fontWeight: "600",
    color: colors.textPrimary,
    fontFamily: webFont,
  },
  heroContainer: {
    paddingTop: 16,
    paddingBottom: 32,
    ...Platform.select({
      web: { paddingHorizontal: 40 },
      default: { paddingHorizontal: 20 },
    }),
  },
  heroCard: {
    minHeight: 380,
    borderRadius: 32,
    padding: 28,
    overflow: "hidden",
    position: "relative",
    justifyContent: "flex-end",
    ...Platform.select({
      ios: { shadowColor: "#7C3AED", shadowOpacity: 0.15, shadowRadius: 30, shadowOffset: { width: 0, height: 12 } },
      android: { elevation: 8 },
      web: { boxShadow: "0 16px 48px rgba(124, 58, 237, 0.15)" },
      default: { elevation: 8 },
    }),
  },
  heroBadge: {
    alignSelf: "flex-start",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: "rgba(255, 255, 255, 0.4)",
    marginBottom: "auto" as any,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.8)",
  },
  heroBadgeText: {
    color: "#5B21B6",
    fontWeight: "700",
    fontSize: 12,
    fontFamily: webFont,
  },
  heroTitle: {
    fontSize: 34,
    lineHeight: 44,
    fontWeight: "900",
    color: "#1E293B",
    fontFamily: displayFont,
    marginBottom: 8,
  },
  heroDescription: {
    fontSize: 16,
    color: "#475569",
    lineHeight: 24,
    fontFamily: webFont,
    marginBottom: 28,
  },
  heroButtons: {
    flexDirection: "row",
    gap: 12,
  },
  heroButtonPrimary: {
    flex: 1,
    height: 54,
    borderRadius: 27,
    alignItems: "center",
    justifyContent: "center",
    ...Platform.select({
      ios: { shadowColor: "#7C3AED", shadowOpacity: 0.3, shadowRadius: 12, shadowOffset: { width: 0, height: 6 } },
      android: { elevation: 6 },
      web: { boxShadow: "0 6px 20px rgba(124, 58, 237, 0.3)" },
    }),
  },
  heroButtonPrimaryText: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 15,
    fontFamily: displayFont,
  },
  heroButtonSecondary: {
    flex: 1,
    height: 54,
    borderRadius: 27,
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 1)",
  },
  heroButtonSecondaryText: {
    color: "#475569",
    fontWeight: "700",
    fontSize: 15,
    fontFamily: displayFont,
  },
  chatDemoCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    marginBottom: 32,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(124, 58, 237, 0.05)",
    ...Platform.select({
      web: { marginHorizontal: 40 },
      default: { marginHorizontal: 20 },
    }),
    ...cardShadow,
  },
  chatDemoHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255,255,255,0.1)",
  },
  chatDemoAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.2)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  chatDemoTitle: {
    color: "#FFFFFF",
    fontWeight: "800",
    fontSize: 16,
    fontFamily: displayFont,
  },
  chatDemoStatus: {
    color: "rgba(255,255,255,0.8)",
    fontSize: 12,
  },
  chatDemoBody: {
    padding: 20,
    backgroundColor: "#FAFAFC",
  },
  chatBubbleAi: {
    backgroundColor: "#FFFFFF",
    padding: 14,
    borderRadius: 20,
    borderBottomLeftRadius: 4,
    alignSelf: "flex-start",
    maxWidth: "85%",
    marginBottom: 12,
    ...Platform.select({
      ios: { shadowColor: "#000", shadowOpacity: 0.03, shadowRadius: 8, shadowOffset: { width: 0, height: 2 } },
      android: { elevation: 1 },
      web: { boxShadow: "0 2px 10px rgba(0,0,0,0.03)" },
    }),
  },
  chatBubbleUser: {
    padding: 14,
    borderRadius: 20,
    borderBottomRightRadius: 4,
    alignSelf: "flex-end",
    maxWidth: "85%",
    marginBottom: 12,
  },
  chatTextAi: {
    color: "#334155",
    fontSize: 14,
    lineHeight: 22,
    fontFamily: webFont,
  },
  chatTextUser: {
    color: "#FFFFFF",
    fontSize: 14,
    lineHeight: 22,
    fontFamily: webFont,
  },
  chatTyping: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    padding: 14,
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderBottomLeftRadius: 4,
    alignSelf: "flex-start",
  },
  typingDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "#C4B5FD",
  },
  chatDemoFooter: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    paddingHorizontal: 16,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.02)",
  },
  chatDemoInput: {
    flex: 1,
    height: 40,
    backgroundColor: "#F1F5F9",
    borderRadius: 20,
    paddingHorizontal: 16,
    marginRight: 12,
  },
  chatDemoInputText: {
    color: "#94A3B8",
    fontSize: 14,
  },
  chatDemoSend: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 32,
    ...Platform.select({
      web: { paddingHorizontal: 40 },
      default: { paddingHorizontal: 24 },
    }),
  },
  statItem: {
    alignItems: "center",
  },
  statValue: {
    fontSize: 24,
    fontWeight: "900",
    color: colors.primary,
    fontFamily: displayFont,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 11,
    color: "#64748B",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  motivationCard: {
    marginBottom: 32,
    borderRadius: 24,
    padding: 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    overflow: "hidden",
    ...Platform.select({
      web: { marginHorizontal: 40 },
      default: { marginHorizontal: 20 },
    }),
  },
  motivationTextWrap: {
    flex: 1,
  },
  motivationTitle: {
    color: "#FFFFFF",
    fontSize: 22,
    fontWeight: "800",
    fontFamily: displayFont,
    marginBottom: 16,
    lineHeight: 30,
  },
  motivationBtn: {
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 999,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.4)",
  },
  motivationBtnText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 13,
  },
  articleCard: {
    marginBottom: 32,
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.03)",
    ...Platform.select({
      web: { marginHorizontal: 40 },
      default: { marginHorizontal: 20 },
    }),
    ...cardShadow,
  },
  articleImgMock: {
    height: 140,
    backgroundColor: "#FDE68A",
    alignItems: "center",
    justifyContent: "center",
  },
  articleContent: {
    padding: 24,
  },
  articleTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1E293B",
    fontFamily: displayFont,
    marginBottom: 8,
  },
  articleDesc: {
    fontSize: 14,
    color: "#64748B",
    lineHeight: 22,
    marginBottom: 16,
  },
  tipRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
    gap: 12,
  },
  tipIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: "#EDE9FE",
    alignItems: "center",
    justifyContent: "center",
  },
  tipText: {
    fontSize: 14,
    color: "#334155",
    fontWeight: "500",
  },
  sectionTitle: {
    fontSize: 22,
    fontWeight: "800",
    color: "#1E293B",
    fontFamily: displayFont,
    marginBottom: 6,
    paddingHorizontal: 20,
  },
  sectionSub: {
    fontSize: 14,
    color: "#64748B",
    marginBottom: 20,
    paddingHorizontal: 20,
  },
  healingGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginBottom: 32,
    ...Platform.select({
      web: { paddingHorizontal: 34 },
      default: { paddingHorizontal: 14 },
    }),
  },
  healingCardWrapper: {
    width: "50%",
    padding: 6,
  },
  healingCard: {
    borderRadius: 24,
    padding: 20,
    minHeight: 160,
    justifyContent: "space-between",
  },
  healingIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "rgba(255,255,255,0.3)",
    alignItems: "center",
    justifyContent: "center",
  },
  healingTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1E293B",
    fontFamily: displayFont,
    marginTop: 16,
  },
  healingSub: {
    fontSize: 12,
    color: "#475569",
    marginTop: 4,
    opacity: 0.8,
  },
  dashCard: {
    marginBottom: 32,
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    padding: 24,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.03)",
    ...Platform.select({
      web: { marginHorizontal: 40 },
      default: { marginHorizontal: 20 },
    }),
    ...cardShadow,
  },
  dashHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  dashTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1E293B",
  },
  dashLink: {
    fontSize: 13,
    color: colors.primary,
    fontWeight: "700",
  },
  chartRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    height: 120,
  },
  chartItem: {
    alignItems: "center",
  },
  chartEmoji: {
    fontSize: 20,
    marginBottom: 8,
  },
  chartBar: {
    width: 24,
    borderRadius: 12,
    backgroundColor: "#EDE9FE",
  },
  chartDay: {
    marginTop: 8,
    fontSize: 12,
    color: "#94A3B8",
    fontWeight: "600",
  },
  insightBox: {
    marginTop: 24,
    backgroundColor: "#F8FAFC",
    borderRadius: 20,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: "#F1F5F9",
  },
  insightText: {
    flex: 1,
    fontSize: 14,
    color: "#475569",
    lineHeight: 22,
  },
  communityCard: {
    marginBottom: 32,
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    padding: 24,
    ...Platform.select({
      web: { marginHorizontal: 40 },
      default: { marginHorizontal: 20 },
    }),
    ...cardShadow,
  },
  userRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 16,
  },
  smallAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: "#F1F5F9",
  },
  userName: {
    fontSize: 16,
    fontWeight: "800",
    color: "#1E293B",
  },
  time: {
    fontSize: 12,
    color: "#94A3B8",
    marginTop: 2,
  },
  postText: {
    fontSize: 15,
    color: "#334155",
    lineHeight: 24,
    marginBottom: 16,
  },
  reactRow: {
    flexDirection: "row",
    gap: 16,
  },
  reactItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#F8FAFC",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  reactText: {
    fontSize: 13,
    color: "#64748B",
    fontWeight: "600",
  },
  eventCard: {
    marginBottom: 32,
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    overflow: "hidden",
    ...Platform.select({
      web: { marginHorizontal: 40 },
      default: { marginHorizontal: 20 },
    }),
    ...cardShadow,
  },
  eventImg: {
    height: 160,
    backgroundColor: "#CCFBF1",
    alignItems: "center",
    justifyContent: "center",
  },
  eventContent: {
    padding: 24,
  },
  eventTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#1E293B",
    marginBottom: 8,
  },
  eventMeta: {
    fontSize: 14,
    color: "#64748B",
    marginBottom: 20,
  },
  joinButton: {
    backgroundColor: "#1E293B",
    paddingVertical: 14,
    borderRadius: 16,
    alignItems: "center",
  },
  joinText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  testiScroll: {
    paddingBottom: 32,
    ...Platform.select({
      web: { paddingHorizontal: 40 },
      default: { paddingHorizontal: 20 },
    }),
  },
  testiCard: {
    width: 280,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 24,
    marginRight: 16,
    ...cardShadow,
  },
  starsRow: {
    flexDirection: "row",
    gap: 4,
    marginBottom: 16,
  },
  testiText: {
    fontSize: 15,
    color: "#334155",
    lineHeight: 24,
    marginBottom: 20,
    fontStyle: "italic",
  },
  testiUserRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  testiAvatar: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#F1F5F9",
  },
  testiName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#1E293B",
  },
  testiRole: {
    fontSize: 12,
    color: "#94A3B8",
  },
  pricingRow: {
    flexDirection: "row",
    marginBottom: 32,
    gap: 16,
    ...Platform.select({
      web: { paddingHorizontal: 40 },
      default: { paddingHorizontal: 20 },
    }),
  },
  priceCard: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: "#E2E8F0",
    alignItems: "center",
  },
  priceCardPro: {
    flex: 1.2,
    backgroundColor: "#FFFFFF",
    borderRadius: 28,
    padding: 24,
    borderWidth: 2,
    borderColor: colors.primary,
    alignItems: "center",
    ...cardShadow,
  },
  priceBadge: {
    position: "absolute",
    top: -12,
    backgroundColor: colors.primary,
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  priceBadgeText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "800",
  },
  priceTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#475569",
    marginBottom: 8,
  },
  priceTitlePro: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.primary,
    marginBottom: 8,
  },
  priceAmount: {
    fontSize: 24,
    fontWeight: "900",
    color: "#1E293B",
  },
  priceAmountPro: {
    fontSize: 28,
    fontWeight: "900",
    color: "#1E293B",
  },
  priceSub: {
    fontSize: 12,
    color: "#94A3B8",
    marginBottom: 20,
  },
  priceBtn: {
    width: "100%",
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: "#F1F5F9",
    alignItems: "center",
  },
  priceBtnPro: {
    width: "100%",
    paddingVertical: 14,
    borderRadius: 14,
    backgroundColor: colors.primary,
    alignItems: "center",
  },
  priceBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#475569",
  },
  priceBtnTextPro: {
    fontSize: 14,
    fontWeight: "800",
    color: "#FFFFFF",
  },
  ctaSection: {
    marginBottom: 32,
    borderRadius: 32,
    padding: 32,
    alignItems: "center",
    overflow: "hidden",
    ...Platform.select({
      web: { marginHorizontal: 40 },
      default: { marginHorizontal: 20 },
    }),
  },
  ctaTitle: {
    fontSize: 28,
    fontWeight: "900",
    color: "#FFFFFF",
    textAlign: "center",
    marginBottom: 12,
    fontFamily: displayFont,
  },
  ctaSub: {
    fontSize: 15,
    color: "rgba(255,255,255,0.8)",
    textAlign: "center",
    marginBottom: 24,
  },
  ctaInputWrap: {
    width: "100%",
    height: 54,
    backgroundColor: "rgba(255,255,255,0.2)",
    borderRadius: 27,
    flexDirection: "row",
    alignItems: "center",
    paddingLeft: 20,
    paddingRight: 6,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.3)",
  },
  ctaInput: {
    flex: 1,
    color: "#FFFFFF",
    fontSize: 15,
  },
  ctaBtn: {
    height: 42,
    paddingHorizontal: 20,
    backgroundColor: "#FFFFFF",
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
  },
  ctaBtnText: {
    color: colors.primary,
    fontWeight: "800",
    fontSize: 14,
  },
  footerWrap: {
    alignItems: "center",
    paddingVertical: 32,
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.05)",
  },
  footerLogo: {
    fontSize: 24,
    fontWeight: "900",
    color: "#94A3B8",
    letterSpacing: 2,
    marginBottom: 16,
  },
  footerLinks: {
    flexDirection: "row",
    gap: 20,
    marginBottom: 16,
  },
  footerLink: {
    fontSize: 13,
    color: "#64748B",
    fontWeight: "500",
  },
  footerCopy: {
    fontSize: 12,
    color: "#CBD5E1",
  },
  footer: {
    height: 86,
    borderRadius: 43,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    marginHorizontal: 20,
    marginBottom: Platform.OS === "ios" ? 32 : 24,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    borderWidth: 1,
    borderColor: "rgba(124, 58, 237, 0.1)",
    ...Platform.select({
      ios: { shadowColor: "#7C3AED", shadowOpacity: 0.1, shadowRadius: 24, shadowOffset: { width: 0, height: 10 } },
      android: { elevation: 12 },
      web: { boxShadow: "0 10px 40px rgba(124, 58, 237, 0.15)" },
    }),
  },
  footerItem: {
    alignItems: "center",
    justifyContent: "center",
    width: 60,
  },
  footerText: {
    marginTop: 4,
    color: "#94A3B8",
    fontWeight: "700",
    fontSize: 10,
    fontFamily: webFont,
  },
  footerPlus: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: colors.primary,
    alignItems: "center",
    justifyContent: "center",
    marginTop: -30,
    borderWidth: 4,
    borderColor: "#FAFAFC",
    ...Platform.select({
      ios: { shadowColor: "#7C3AED", shadowOpacity: 0.4, shadowRadius: 16, shadowOffset: { width: 0, height: 8 } },
      android: { elevation: 8 },
      web: { boxShadow: "0 8px 24px rgba(124, 58, 237, 0.4)" },
    }),
  },
  sidebar: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 280,
    backgroundColor: "rgba(255,255,255,0.9)",
    padding: 24,
    borderTopRightRadius: 32,
    borderBottomRightRadius: 32,
    borderRightWidth: 1,
    borderColor: "rgba(124, 58, 237, 0.1)",
    ...Platform.select({
      ios: { shadowColor: "#7C3AED", shadowOpacity: 0.15, shadowRadius: 32, shadowOffset: { width: 10, height: 0 } },
      android: { elevation: 16 },
      web: { boxShadow: "10px 0 48px rgba(124, 58, 237, 0.1)", backdropFilter: "blur(20px)" },
    }),
    zIndex: 99999,
  },
  logoBox: {
    alignItems: "center",
    marginBottom: 32,
    paddingTop: 20,
  },
  sideItem: {
    height: 52,
    borderRadius: 16,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    marginBottom: 8,
  },
  sideItemActive: {
    backgroundColor: "#F3E8FF",
  },
  sideText: {
    marginLeft: 14,
    fontSize: 15,
    color: "#64748B",
    fontWeight: "600",
  },
  sideTextActive: {
    color: colors.primary,
    fontWeight: "800",
  },
  reminderCard: {
    marginTop: "auto" as any,
    padding: 20,
    borderRadius: 24,
    backgroundColor: "#F5F3FF",
    borderWidth: 1,
    borderColor: "#EDE9FE",
  },
  reminderTitle: {
    marginTop: 12,
    color: colors.primary,
    fontWeight: "800",
    fontSize: 16,
  },
  reminderText: {
    marginTop: 8,
    color: "#64748B",
    lineHeight: 22,
    fontSize: 13,
  },
  row: {
    flexDirection: "column",
    gap: 16,
    marginBottom: 16,
  },
});
